# Generated by Django 4.0.1 on 2022-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('project_info', models.TextField(max_length=500)),
                ('technologies_used', models.TextField()),
                ('github_link', models.URLField()),
                ('website', models.URLField()),
                ('project_image', models.ImageField(upload_to='uploads/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
