# Generated by Django 4.0.1 on 2022-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='primary_language',
            field=models.CharField(default='Python', max_length=50),
        ),
    ]
