# Generated by Django 4.0.1 on 2022-02-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='Images',
        ),
    ]
